site_name: Project Olly Documentation
nav:
    - Home: index.md
    - Changelog: changelog.md
    - Single Elimination Tournaments: singletournaments.md
    - Support: support.md
    - Teams: teams.md
    - Staff Panel: staff.md
    - Profiles: profiles.md
    - Matches: matches.md
    - News: news.md
    - Wagers: wagers.md
theme: readthedocs